# Generated by Django 3.0.7 on 2020-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
