# Generated by Django 3.0.7 on 2020-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='apply_text',
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_gender',
            field=models.CharField(blank=True, choices=[('0', '여자'), ('1', '남자')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_house',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_housemate',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_job',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_pets',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='apply_phone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
