# Generated by Django 3.0.7 on 2020-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0005_auto_20200620_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_gender',
            field=models.CharField(choices=[('0', '여자'), ('1', '남자')], max_length=10, null=True),
        ),
    ]
