# Generated by Django 3.0.7 on 2020-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_auto_20200620_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_gender',
            field=models.CharField(choices=[('여자', '여자'), ('남자', '남자')], max_length=10, null=True),
        ),
    ]
