# Generated by Django 3.0.7 on 2020-06-18 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('review_image', models.ImageField(blank=True, null=True, upload_to='review/%Y/%m/%d')),
                ('review_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_published_date', models.DateTimeField(blank=True, null=True)),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
